[package]
name = "example-ex-engine-api-ext"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true

[dependencies]
# reth
reth-db = { workspace = true, features = ["op", "test-utils"] }
reth-ethereum = { workspace = true, features = ["node", "pool", "node-api", "cli", "exex"] }
reth-node-builder.workspace = true
reth-optimism-consensus.workspace = true

reth-node-api.workspace = true
reth-rpc-api.workspace = true
reth-tracing.workspace = true
reth-provider.workspace = true
reth-optimism-node.workspace = true
reth-optimism-chainspec.workspace = true
reth-op = { workspace = true, features = ["full", "cli"] }


example-custom-node = { path = "../custom-node" }

# alloy 
alloy-rpc-types-engine.workspace = true

async-trait.workspace = true
clap = { workspace = true, features = ["derive"] }
eyre.workspace = true
jsonrpsee.workspace = true
futures.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["sync"] }


