[package]
name = "example-custom-node"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true

[dependencies]
# reth
reth-chain-state.workspace = true
reth-codecs.workspace = true
reth-network-peers.workspace = true
reth-node-builder.workspace = true
reth-optimism-forks.workspace = true
reth-optimism-consensus.workspace = true
reth-op = { workspace = true, features = ["node", "pool"] }
reth-payload-builder.workspace = true
reth-rpc-api.workspace = true
reth-rpc-engine-api.workspace = true
reth-ethereum = { workspace = true, features = ["node-api", "network", "evm", "pool"] }

reth-basic-payload-builder.workspace = true
reth-chainspec.workspace = true
reth-cli.workspace = true
reth-cli-commands.workspace = true
reth-cli-runner.workspace = true
reth-cli-util.workspace = true
reth-codecs-derive.workspace = true
reth-config.workspace = true
reth-consensus.workspace = true
reth-consensus-common.workspace = true
reth-consensus-debug-client.workspace = true
reth-db.workspace = true
reth-db-api.workspace = true
reth-db-common.workspace = true
reth-db-models.workspace = true
reth-discv4.workspace = true
reth-discv5.workspace = true
reth-dns-discovery.workspace = true
reth-downloaders.workspace = true
reth-e2e-test-utils.workspace = true
reth-ecies.workspace = true
reth-engine-local.workspace = true
reth-engine-primitives.workspace = true
reth-engine-tree.workspace = true
reth-engine-service.workspace = true
reth-engine-util.workspace = true
reth-era.workspace = true
reth-era-downloader.workspace = true
reth-era-utils.workspace = true
reth-errors.workspace = true
reth-eth-wire.workspace = true
reth-eth-wire-types.workspace = true
reth-ethereum-cli.workspace = true
reth-ethereum-consensus.workspace = true
reth-ethereum-engine-primitives.workspace = true
reth-ethereum-forks.workspace = true
reth-ethereum-payload-builder.workspace = true
reth-ethereum-primitives.workspace = true
reth-etl.workspace = true
reth-evm.workspace = true
reth-evm-ethereum.workspace = true
reth-optimism-evm.workspace = true
reth-execution-errors.workspace = true
reth-execution-types.workspace = true
reth-exex.workspace = true
reth-exex-test-utils.workspace = true
reth-exex-types.workspace = true
reth-fs-util.workspace = true
reth-invalid-block-hooks.workspace = true
reth-ipc.workspace = true
reth-libmdbx.workspace = true
reth-mdbx-sys.workspace = true
reth-metrics.workspace = true
reth-net-banlist.workspace = true
reth-net-nat.workspace = true
reth-network.workspace = true
reth-network-api.workspace = true
reth-network-p2p.workspace = true
reth-network-types.workspace = true
reth-nippy-jar.workspace = true
reth-node-api.workspace = true
reth-node-core.workspace = true
reth-node-ethereum.workspace = true
reth-node-events.workspace = true
reth-node-metrics.workspace = true
reth-optimism-node.workspace = true
reth-node-types.workspace = true
reth-optimism-chainspec.workspace = true
reth-optimism-cli.workspace = true
reth-optimism-payload-builder.workspace = true
reth-optimism-primitives.workspace = true
reth-optimism-rpc.workspace = true
reth-optimism-storage.workspace = true
reth-optimism-txpool.workspace = true
reth-payload-builder-primitives.workspace = true
reth-payload-primitives.workspace = true
reth-payload-validator.workspace = true
reth-payload-util.workspace = true
reth-primitives.workspace = true
reth-primitives-traits.workspace = true
reth-provider.workspace = true
reth-prune.workspace = true
reth-prune-types.workspace = true
reth-revm.workspace = true
reth-rpc.workspace = true
reth-rpc-api-testing-util.workspace = true
reth-rpc-builder.workspace = true
reth-rpc-eth-api.workspace = true
reth-rpc-eth-types.workspace = true
reth-rpc-layer.workspace = true
reth-rpc-server-types.workspace = true
reth-rpc-types-compat.workspace = true
reth-stages.workspace = true
reth-stages-api.workspace = true
reth-stages-types.workspace = true
reth-stateless.workspace = true
reth-static-file.workspace = true
reth-static-file-types.workspace = true
reth-storage-api.workspace = true
reth-storage-errors.workspace = true
reth-tasks.workspace = true
reth-testing-utils.workspace = true
reth-tokio-util.workspace = true
reth-tracing.workspace = true
reth-transaction-pool.workspace = true
reth-trie.workspace = true
reth-trie-common.workspace = true
reth-trie-db.workspace = true
reth-trie-parallel.workspace = true
reth-trie-sparse.workspace = true
reth-zstd-compressors.workspace = true
reth-ress-protocol.workspace = true
reth-ress-provider.workspace = true

# revm
revm.workspace = true
revm-primitives.workspace = true

# alloy
alloy-network.workspace = true
alloy-consensus = { workspace = true, features = ["serde"] }
alloy-eips.workspace = true
alloy-evm.workspace = true
alloy-genesis.workspace = true
alloy-op-evm.workspace = true
alloy-primitives.workspace = true
alloy-rlp.workspace = true
alloy-serde.workspace = true
alloy-rpc-types-engine.workspace = true
op-alloy-consensus.workspace = true
op-alloy-rpc-types-engine.workspace = true
op-revm.workspace = true

# misc
async-trait.workspace = true
derive_more.workspace = true
eyre.workspace = true
jsonrpsee.workspace = true
serde.workspace = true
tokio.workspace = true

modular-bitfield.workspace = true

[dev-dependencies]
test-fuzz.workspace = true

[features]
arbitrary = [
    "alloy-consensus/arbitrary",
    "alloy-eips/arbitrary",
    "alloy-primitives/arbitrary",
    "alloy-serde/arbitrary",
    "op-alloy-consensus/arbitrary",
    "op-alloy-rpc-types-engine/arbitrary",
    "reth-codecs/arbitrary",
    "reth-op/arbitrary",
    "revm-primitives/arbitrary",
    "revm/arbitrary",
    "reth-ethereum/arbitrary",
    "alloy-rpc-types-engine/arbitrary",
]
default = []
